# Site settings
title: Trappings of Code
email: williams.jackj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developer of C#, ASP.NET Core, JavaScript, Node things - as well as anything else I can find at 1 A.M.
  Lover of fresh air. Father, friend, son.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jackjwilliams.github.io" # the base hostname & protocol for your site
twitter_username: jackkedd
github_username:  jackjwilliams
repository: jackjwilliams/jackjwilliams.github.io
# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
